# Generated by Django 4.2.7 on 2024-02-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
