# Generated by Django 4.2.7 on 2024-02-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_article_title_alter_headline_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='publishedAt',
        ),
    ]
